spring:
  application:
    name: nba-stats
  datasource:
    #url: jdbc:postgresql://skyhawk-db-1:5432/nba_stats
    url: jdbc:postgresql://localhost:5432/nba_stats
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: true

server:
  port: 8080
  tomcat:
    max-threads: 200
    min-spare-threads: 10

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 